blank_issues_enabled: false
contact_links:
  - name: '📖 Read the README'
    url: https://github.com/pstepanovum/PSInstagram#readme
    about: Find answers to the most commonly asked questions
  - name: '❓ Need Help?'
    url: https://github.com/pstepanovum/PSInstagram/issues
    about: Visit the PSInstagram issues page to get support
